version: "2"
services:
  redmine:
    image: eeacms/redmine:3.4-3.6
    restart: unless-stopped
    labels:
      eu.europa.eionet.taskman: "yes"
    ports:
    - "8080:3000"
    volumes:
      - ./.email.secret:/var/local/environment/vars:z
      - ./plugins:/install_plugins:z
      - redmine-files:/usr/src/redmine/files
      - redmine-tmp:/usr/src/redmine/tmp
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-github:/var/local/redmine/github/
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .redmine.secret
    depends_on:
    - mysql
    - postfix
    - memcached

  mysql:
    image: mysql:5.7.10
    restart: unless-stopped
    labels:
      eu.europa.eionet.taskman: "yes"
    volumes:
    - ./backup/:/var/local/backup/:z
    - mysql-data:/var/lib/mysql
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .mysql.secret
    command:
    - "--query-cache-size=0"
    - "--query-cache-limit=64M"
    - "--query-cache-type=0"
    - "--innodb-buffer-pool-size=1G"
    - "--innodb-buffer-pool-instances=4"
    - "--net-read-timeout=7200"
    - "--net-write-timeout=7200"
    - "--max-allowed-packet=128M"
    - "--tmp-table-size=384M"
    - "--max-heap-table-size=384M"
    - "--join-buffer-size=256M"


  mysql-backup:
    image: eeacms/mysql-backup
    restart: unless-stopped
    labels:
      eu.europa.eionet.taskman: "yes"
    links:
     - mysql:db
    env_file:
     - .mysql.secret
    volumes:
     - /var/lib/docker/volumes/taskman_mysql_backup/:/db
    environment:
     - DB_DUMP_TARGET=/db
     - DB_DUMP_FREQ=1440
     - DB_DUMP_BEGIN=1720
     - DB_DUMP_FILENAME=taskman_db_dump
     - DB_DUMP_FILEDATE=no

  postfix:
    image: eeacms/postfix:2.10-3.1
    restart: unless-stopped
    labels:
      eu.europa.eionet.taskman: "yes"
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .postfix.secret

  memcached:
    image: memcached:1.4.36
    restart: unless-stopped
    labels:
      eu.europa.eionet.taskman: "yes"
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - "-m"
    - "2048"

volumes:
  redmine-files:
  redmine-tmp:
  redmine-github:
  redmine-plugins:
  mysql-data:
