version: "2"
services:
  redmine:
    image: eeacms/redmine:latest

  postfix:
    image: eaudeweb/mailtrap
    ports:
      - "8081:80"

  logspout:
    image: gliderlabs/logspout:v3.1
    restart: unless-stopped
    command: 'syslog://logcentral.eea.europa.eu:1514?filter.label=eu.europa.eionet.taskman:yes'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SYSLOG_HOSTNAME: "taskman.devecs.eea.europa.eu"
