version: "2"
services:
  apache:
    image: eeacms/apache:2.4-2.1
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    environment:
      APACHE_MODULES: "http2_module"
      APACHE_CONFIG: |-
        <VirtualHost *:80>
            ServerName taskman.eionet.europa.eu
            RewriteEngine On
            RewriteRule ^(.*)$$ https://taskman.eionet.europa.eu$$1 [R=permanent,L]
        </VirtualHost>
        <VirtualHost *:443>
            ServerName taskman.eionet.europa.eu
            Protocols h2 http/1.1
            H2ModernTLSOnly off
            KeepAliveTimeout 30
            SSLEngine on
            SSLProtocol ALL -SSLv2 -SSLv3
            SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
            SSLHonorCipherOrder on
            SSLCompression off
            SSLCertificateFile /certs/server.crt
            SSLCertificateKeyFile /certs/server.key

            SSLOptions +StdEnvVars

            ErrorDocument 404 /errors/404.html
            ErrorDocument 500 /errors/50x.html
            ErrorDocument 501 /errors/50x.html
            ErrorDocument 502 /errors/maintenance.html
            ErrorDocument 503 /errors/maintenance.html
            ErrorDocument 504 /errors/50x.html
            ErrorDocument 505 /errors/50x.html

            <Location /errors>
                ProxyPass !
            </Location>

            ProxyTimeout 600
            ProxyRequests Off

            RewriteEngine On

            LimitRequestBody 104857600
            RequestHeader set Host "%{HTTP_HOST}s"
            RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
            RequestHeader set X-Forwarded-For "%{X-Forwarded-For}s"
            RequestHeader set X-Forwarded-Proto https
            RequestHeader set X-Frame-Options SAMEORIGIN
            RewriteRule ^(.*)$$ http://kvm-cph-14.pdmz.eea:8080$$1 [P]


        </VirtualHost>
      TZ: "Europe/Copenhagen"
    volumes:
    - /var/local/deploy/www-eea-certs/bundle-eionet.crt:/certs/server.crt:ro
    - /var/local/deploy/www-eea-certs/server-eionet.key:/certs/server.key:ro
    - ./html:/usr/local/apache2/htdocs/errors
networks:
    default:
        driver: bridge
        driver_opts:
           com.docker.network.driver.mtu: 1450

